from typing import Optional


class WriteStream:
    def __init__(self):
        ...

    def __repr__(self):
        ...

    def write_bytes(self, data: bytes | bytearray | int) -> None:
        ...

    def write_byte(self, value: int) -> None:
        ...
    
    def write_int(self, value: int) -> None:
        ...

    def write_long(self, value: int) -> None:
        ...

    def write_sq_string(self, value: str) -> None:
        ...

    def write_string(self, value: str) -> None:
        ...

    def write_boolean(self, value: bool) -> None:
        ...

    def write_float(self, value: float) -> None:
        ...

    def get_raw_buffer(self) -> bytes:
        ...


class ReadStream:
    def __init__(self, data: Optional[bytes]):
        ...

    def __repr__(self):
        ...

    def read(self, length: int) -> bytes:
        ...

    def read_byte(self) -> int:
        ...

    def read_bytes(self, length: int) -> bytes:
        ...

    def read_int(self) -> int:
        ...

    def read_long(self) -> int:
        ...

    def read_sq_string(self) -> str:
        ...

    def read_string(self) -> str:
        ...

    def read_boolean(self) -> bool:
        ...

    def read_float(self) -> float:
        ...

    def get_raw_buffer(self) -> bytes:
        ...