name: Setup Python & Cargo
description: Setup Python & Cargo

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - uses: pdm-project/setup-pdm@v4
      name: Setup PDM
      with:
        python-version: ${{ inputs.python-version }}
        architecture: "x64"
        cache: true

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable