/* automatically generated by rust-bindgen 0.71.1 */

pub const PLUGIN_API_MAJOR: u32 = 2;
pub const PLUGIN_API_MINOR: u32 = 1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ServerSettings {
    pub structSize: u32,
    pub serverName: [::std::os::raw::c_char; 128usize],
    pub maxPlayers: u32,
    pub port: u32,
    pub flags: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PluginInfo {
    pub structSize: u32,
    pub pluginId: u32,
    pub name: [::std::os::raw::c_char; 32usize],
    pub pluginVersion: u32,
    pub apiMajorVersion: u16,
    pub apiMinorVersion: u16,
}
pub const vcmpError_vcmpErrorNone: vcmpError = 0;
pub const vcmpError_vcmpErrorNoSuchEntity: vcmpError = 1;
pub const vcmpError_vcmpErrorBufferTooSmall: vcmpError = 2;
pub const vcmpError_vcmpErrorTooLargeInput: vcmpError = 3;
pub const vcmpError_vcmpErrorArgumentOutOfBounds: vcmpError = 4;
pub const vcmpError_vcmpErrorNullArgument: vcmpError = 5;
pub const vcmpError_vcmpErrorPoolExhausted: vcmpError = 6;
pub const vcmpError_vcmpErrorInvalidName: vcmpError = 7;
pub const vcmpError_vcmpErrorRequestDenied: vcmpError = 8;
pub const vcmpError_forceSizeVcmpError: vcmpError = 2147483647;
pub type vcmpError = ::std::os::raw::c_int;
pub const vcmpEntityPool_vcmpEntityPoolVehicle: vcmpEntityPool = 1;
pub const vcmpEntityPool_vcmpEntityPoolObject: vcmpEntityPool = 2;
pub const vcmpEntityPool_vcmpEntityPoolPickup: vcmpEntityPool = 3;
pub const vcmpEntityPool_vcmpEntityPoolRadio: vcmpEntityPool = 4;
pub const vcmpEntityPool_vcmpEntityPoolPlayer: vcmpEntityPool = 5;
pub const vcmpEntityPool_vcmpEntityReserved1: vcmpEntityPool = 6;
pub const vcmpEntityPool_vcmpEntityPoolBlip: vcmpEntityPool = 7;
pub const vcmpEntityPool_vcmpEntityPoolCheckPoint: vcmpEntityPool = 8;
pub const vcmpEntityPool_forceSizeVcmpEntityPool: vcmpEntityPool = 2147483647;
pub type vcmpEntityPool = ::std::os::raw::c_int;
pub const vcmpDisconnectReason_vcmpDisconnectReasonTimeout: vcmpDisconnectReason = 0;
pub const vcmpDisconnectReason_vcmpDisconnectReasonQuit: vcmpDisconnectReason = 1;
pub const vcmpDisconnectReason_vcmpDisconnectReasonKick: vcmpDisconnectReason = 2;
pub const vcmpDisconnectReason_vcmpDisconnectReasonCrash: vcmpDisconnectReason = 3;
pub const vcmpDisconnectReason_vcmpDisconnectReasonAntiCheat: vcmpDisconnectReason = 4;
pub const vcmpDisconnectReason_forceSizeVcmpDisconnectReason: vcmpDisconnectReason = 2147483647;
pub type vcmpDisconnectReason = ::std::os::raw::c_int;
pub const vcmpBodyPart_vcmpBodyPartBody: vcmpBodyPart = 0;
pub const vcmpBodyPart_vcmpBodyPartTorso: vcmpBodyPart = 1;
pub const vcmpBodyPart_vcmpBodyPartLeftArm: vcmpBodyPart = 2;
pub const vcmpBodyPart_vcmpBodyPartRightArm: vcmpBodyPart = 3;
pub const vcmpBodyPart_vcmpBodyPartLeftLeg: vcmpBodyPart = 4;
pub const vcmpBodyPart_vcmpBodyPartRightLeg: vcmpBodyPart = 5;
pub const vcmpBodyPart_vcmpBodyPartHead: vcmpBodyPart = 6;
pub const vcmpBodyPart_vcmpBodyPartInVehicle: vcmpBodyPart = 7;
pub const vcmpBodyPart_forceSizeVcmpBodyPart: vcmpBodyPart = 2147483647;
pub type vcmpBodyPart = ::std::os::raw::c_int;
pub const vcmpPlayerState_vcmpPlayerStateNone: vcmpPlayerState = 0;
pub const vcmpPlayerState_vcmpPlayerStateNormal: vcmpPlayerState = 1;
pub const vcmpPlayerState_vcmpPlayerStateAim: vcmpPlayerState = 2;
pub const vcmpPlayerState_vcmpPlayerStateDriver: vcmpPlayerState = 3;
pub const vcmpPlayerState_vcmpPlayerStatePassenger: vcmpPlayerState = 4;
pub const vcmpPlayerState_vcmpPlayerStateEnterDriver: vcmpPlayerState = 5;
pub const vcmpPlayerState_vcmpPlayerStateEnterPassenger: vcmpPlayerState = 6;
pub const vcmpPlayerState_vcmpPlayerStateExit: vcmpPlayerState = 7;
pub const vcmpPlayerState_vcmpPlayerStateUnspawned: vcmpPlayerState = 8;
pub const vcmpPlayerState_forceSizeVcmpPlayerState: vcmpPlayerState = 2147483647;
pub type vcmpPlayerState = ::std::os::raw::c_int;
pub const vcmpPlayerUpdate_vcmpPlayerUpdateNormal: vcmpPlayerUpdate = 0;
pub const vcmpPlayerUpdate_vcmpPlayerUpdateAimingDeprecated: vcmpPlayerUpdate = 1;
pub const vcmpPlayerUpdate_vcmpPlayerUpdateDriver: vcmpPlayerUpdate = 2;
pub const vcmpPlayerUpdate_vcmpPlayerUpdatePassenger: vcmpPlayerUpdate = 3;
pub const vcmpPlayerUpdate_forceSizeVcmpPlayerUpdate: vcmpPlayerUpdate = 2147483647;
pub type vcmpPlayerUpdate = ::std::os::raw::c_int;
pub const vcmpPlayerVehicle_vcmpPlayerVehicleOut: vcmpPlayerVehicle = 0;
pub const vcmpPlayerVehicle_vcmpPlayerVehicleEntering: vcmpPlayerVehicle = 1;
pub const vcmpPlayerVehicle_vcmpPlayerVehicleExiting: vcmpPlayerVehicle = 2;
pub const vcmpPlayerVehicle_vcmpPlayerVehicleIn: vcmpPlayerVehicle = 3;
pub const vcmpPlayerVehicle_forceSizeVcmpPlayerVehicle: vcmpPlayerVehicle = 2147483647;
pub type vcmpPlayerVehicle = ::std::os::raw::c_int;
pub const vcmpVehicleSync_vcmpVehicleSyncNone: vcmpVehicleSync = 0;
pub const vcmpVehicleSync_vcmpVehicleSyncDriver: vcmpVehicleSync = 1;
pub const vcmpVehicleSync_vcmpVehicleSyncPassenger: vcmpVehicleSync = 3;
pub const vcmpVehicleSync_vcmpVehicleSyncNear: vcmpVehicleSync = 4;
pub const vcmpVehicleSync_forceSizeVcmpVehicleSync: vcmpVehicleSync = 2147483647;
pub type vcmpVehicleSync = ::std::os::raw::c_int;
pub const vcmpVehicleUpdate_vcmpVehicleUpdateDriverSync: vcmpVehicleUpdate = 0;
pub const vcmpVehicleUpdate_vcmpVehicleUpdateOtherSync: vcmpVehicleUpdate = 1;
pub const vcmpVehicleUpdate_vcmpVehicleUpdatePosition: vcmpVehicleUpdate = 2;
pub const vcmpVehicleUpdate_vcmpVehicleUpdateHealth: vcmpVehicleUpdate = 4;
pub const vcmpVehicleUpdate_vcmpVehicleUpdateColour: vcmpVehicleUpdate = 5;
pub const vcmpVehicleUpdate_vcmpVehicleUpdateRotation: vcmpVehicleUpdate = 6;
pub const vcmpVehicleUpdate_forceSizeVcmpVehicleUpdate: vcmpVehicleUpdate = 2147483647;
pub type vcmpVehicleUpdate = ::std::os::raw::c_int;
pub const vcmpServerOption_vcmpServerOptionSyncFrameLimiter: vcmpServerOption = 0;
pub const vcmpServerOption_vcmpServerOptionFrameLimiter: vcmpServerOption = 1;
pub const vcmpServerOption_vcmpServerOptionTaxiBoostJump: vcmpServerOption = 2;
pub const vcmpServerOption_vcmpServerOptionDriveOnWater: vcmpServerOption = 3;
pub const vcmpServerOption_vcmpServerOptionFastSwitch: vcmpServerOption = 4;
pub const vcmpServerOption_vcmpServerOptionFriendlyFire: vcmpServerOption = 5;
pub const vcmpServerOption_vcmpServerOptionDisableDriveBy: vcmpServerOption = 6;
pub const vcmpServerOption_vcmpServerOptionPerfectHandling: vcmpServerOption = 7;
pub const vcmpServerOption_vcmpServerOptionFlyingCars: vcmpServerOption = 8;
pub const vcmpServerOption_vcmpServerOptionJumpSwitch: vcmpServerOption = 9;
pub const vcmpServerOption_vcmpServerOptionShowMarkers: vcmpServerOption = 10;
pub const vcmpServerOption_vcmpServerOptionOnlyShowTeamMarkers: vcmpServerOption = 11;
pub const vcmpServerOption_vcmpServerOptionStuntBike: vcmpServerOption = 12;
pub const vcmpServerOption_vcmpServerOptionShootInAir: vcmpServerOption = 13;
pub const vcmpServerOption_vcmpServerOptionShowNameTags: vcmpServerOption = 14;
pub const vcmpServerOption_vcmpServerOptionJoinMessages: vcmpServerOption = 15;
pub const vcmpServerOption_vcmpServerOptionDeathMessages: vcmpServerOption = 16;
pub const vcmpServerOption_vcmpServerOptionChatTagsEnabled: vcmpServerOption = 17;
pub const vcmpServerOption_vcmpServerOptionUseClasses: vcmpServerOption = 18;
pub const vcmpServerOption_vcmpServerOptionWallGlitch: vcmpServerOption = 19;
pub const vcmpServerOption_vcmpServerOptionDisableBackfaceCulling: vcmpServerOption = 20;
pub const vcmpServerOption_vcmpServerOptionDisableHeliBladeDamage: vcmpServerOption = 21;
pub const vcmpServerOption_vcmpServerOptionDisableCrouch: vcmpServerOption = 22;
pub const vcmpServerOption_forceSizeVcmpServerOption: vcmpServerOption = 2147483647;
pub type vcmpServerOption = ::std::os::raw::c_int;
pub const vcmpPlayerOption_vcmpPlayerOptionControllable: vcmpPlayerOption = 0;
pub const vcmpPlayerOption_vcmpPlayerOptionDriveBy: vcmpPlayerOption = 1;
pub const vcmpPlayerOption_vcmpPlayerOptionWhiteScanlines: vcmpPlayerOption = 2;
pub const vcmpPlayerOption_vcmpPlayerOptionGreenScanlines: vcmpPlayerOption = 3;
pub const vcmpPlayerOption_vcmpPlayerOptionWidescreen: vcmpPlayerOption = 4;
pub const vcmpPlayerOption_vcmpPlayerOptionShowMarkers: vcmpPlayerOption = 5;
pub const vcmpPlayerOption_vcmpPlayerOptionCanAttack: vcmpPlayerOption = 6;
pub const vcmpPlayerOption_vcmpPlayerOptionHasMarker: vcmpPlayerOption = 7;
pub const vcmpPlayerOption_vcmpPlayerOptionChatTagsEnabled: vcmpPlayerOption = 8;
pub const vcmpPlayerOption_vcmpPlayerOptionDrunkEffectsDeprecated: vcmpPlayerOption = 9;
pub const vcmpPlayerOption_vcmpPlayerOptionBleeding: vcmpPlayerOption = 10;
pub const vcmpPlayerOption_forceSizeVcmpPlayerOption: vcmpPlayerOption = 2147483647;
pub type vcmpPlayerOption = ::std::os::raw::c_int;
pub const vcmpVehicleOption_vcmpVehicleOptionDoorsLocked: vcmpVehicleOption = 0;
pub const vcmpVehicleOption_vcmpVehicleOptionAlarm: vcmpVehicleOption = 1;
pub const vcmpVehicleOption_vcmpVehicleOptionLights: vcmpVehicleOption = 2;
pub const vcmpVehicleOption_vcmpVehicleOptionRadioLocked: vcmpVehicleOption = 3;
pub const vcmpVehicleOption_vcmpVehicleOptionGhost: vcmpVehicleOption = 4;
pub const vcmpVehicleOption_vcmpVehicleOptionSiren: vcmpVehicleOption = 5;
pub const vcmpVehicleOption_vcmpVehicleOptionSingleUse: vcmpVehicleOption = 6;
pub const vcmpVehicleOption_vcmpVehicleOptionEngineDisabled: vcmpVehicleOption = 7;
pub const vcmpVehicleOption_vcmpVehicleOptionBootOpen: vcmpVehicleOption = 8;
pub const vcmpVehicleOption_vcmpVehicleOptionBonnetOpen: vcmpVehicleOption = 9;
pub const vcmpVehicleOption_forceSizeVcmpVehicleOption: vcmpVehicleOption = 2147483647;
pub type vcmpVehicleOption = ::std::os::raw::c_int;
pub const vcmpPickupOption_vcmpPickupOptionSingleUse: vcmpPickupOption = 0;
pub const vcmpPickupOption_forceSizeVcmpPickupOption: vcmpPickupOption = 2147483647;
pub type vcmpPickupOption = ::std::os::raw::c_int;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionDataSentPerSecond:
    vcmpNetworkStatisticsOption = 0;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionDataResentPerSecond:
    vcmpNetworkStatisticsOption = 1;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionDataReceivedPerSecond:
    vcmpNetworkStatisticsOption = 2;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionDataDiscardedPerSecond:
    vcmpNetworkStatisticsOption = 3;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionAllBytesSentPerSecond:
    vcmpNetworkStatisticsOption = 4;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionAllBytesReceivedPerSecond:
    vcmpNetworkStatisticsOption = 5;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionDataSentTotal:
    vcmpNetworkStatisticsOption = 6;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionDataResentTotal:
    vcmpNetworkStatisticsOption = 7;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionDataReceivedTotal:
    vcmpNetworkStatisticsOption = 8;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionDataDiscardedTotal:
    vcmpNetworkStatisticsOption = 9;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionAllBytesSentTotal:
    vcmpNetworkStatisticsOption = 10;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionAllBytesReceivedTotal:
    vcmpNetworkStatisticsOption = 11;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionMessagesWaiting:
    vcmpNetworkStatisticsOption = 12;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionMessagesResending:
    vcmpNetworkStatisticsOption = 13;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionBytesResending:
    vcmpNetworkStatisticsOption = 14;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionPacketLossPerSecond:
    vcmpNetworkStatisticsOption = 15;
pub const vcmpNetworkStatisticsOption_vcmpNetworkStatisticsOptionPacketLossTotal:
    vcmpNetworkStatisticsOption = 16;
pub const vcmpNetworkStatisticsOption_forceSizeVcmpNetworkStatisticsOption:
    vcmpNetworkStatisticsOption = 2147483647;
pub type vcmpNetworkStatisticsOption = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct PluginFuncs {
    pub structSize: u32,
    #[doc = " Plugin system"]
    pub GetServerVersion: unsafe extern "C" fn() -> u32,
    pub GetServerSettings:
        unsafe extern "C" fn(settings: *mut ServerSettings) -> vcmpError,
    pub ExportFunctions: 
        unsafe extern "C" fn(
            pluginId: i32,
            functionList: *mut *const ::std::os::raw::c_void,
            size: usize,
        ) -> vcmpError,
    pub GetNumberOfPlugins: unsafe extern "C" fn() -> u32,
    pub GetPluginInfo: 
        unsafe extern "C" fn(pluginId: i32, pluginInfo: *mut PluginInfo) -> vcmpError,
    pub FindPlugin: 
        unsafe extern "C" fn(pluginName: *const ::std::os::raw::c_char) -> i32,
    pub GetPluginExports: 
        unsafe extern "C" fn(
            pluginId: i32,
            exportCount: *mut usize,
        ) -> *mut *const ::std::os::raw::c_void,
    pub SendPluginCommand: 
        unsafe extern "C" fn(
            commandIdentifier: u32,
            format: *const ::std::os::raw::c_char,
            ...
        ) -> vcmpError,
    pub GetTime: unsafe extern "C" fn() -> u64,
    pub LogMessage: 
        unsafe extern "C" fn(format: *const ::std::os::raw::c_char, ...) -> vcmpError,
    pub GetLastError: unsafe extern "C" fn() -> vcmpError,
    #[doc = " Client messages"]
    pub SendClientScriptData: 
        unsafe extern "C" fn(
            playerId: i32,
            data: *const ::std::os::raw::c_void,
            size: usize,
        ) -> vcmpError,
    pub SendClientMessage: 
        unsafe extern "C" fn(
            playerId: i32,
            colour: u32,
            format: *const ::std::os::raw::c_char,
            ...
        ) -> vcmpError,
    pub SendGameMessage: 
        unsafe extern "C" fn(
            playerId: i32,
            type_: i32,
            format: *const ::std::os::raw::c_char,
            ...
        ) -> vcmpError,
    pub SetServerName: 
        unsafe extern "C" fn(text: *const ::std::os::raw::c_char) -> vcmpError,
    pub GetServerName: 
        unsafe extern "C" fn(buffer: *mut ::std::os::raw::c_char, size: usize) -> vcmpError,
    pub SetMaxPlayers: unsafe extern "C" fn(maxPlayers: u32) -> vcmpError,
    pub GetMaxPlayers: unsafe extern "C" fn() -> u32,
    pub SetServerPassword: 
        unsafe extern "C" fn(password: *const ::std::os::raw::c_char) -> vcmpError,
    pub GetServerPassword: 
        unsafe extern "C" fn(buffer: *mut ::std::os::raw::c_char, size: usize) -> vcmpError,
    pub SetGameModeText: 
        unsafe extern "C" fn(gameMode: *const ::std::os::raw::c_char) -> vcmpError,
    pub GetGameModeText: 
        unsafe extern "C" fn(buffer: *mut ::std::os::raw::c_char, size: usize) -> vcmpError,
    pub ShutdownServer: unsafe extern "C" fn(),
    pub SetServerOption: 
        unsafe extern "C" fn(option: vcmpServerOption, toggle: u8) -> vcmpError,
    pub GetServerOption:
        unsafe extern "C" fn(option: vcmpServerOption) -> u8,
    pub SetWorldBounds:
        unsafe extern "C" fn(maxX: f32, minX: f32, maxY: f32, minY: f32),
    pub GetWorldBounds: 
        unsafe extern "C" fn(
            maxXOut: *mut f32,
            minXOut: *mut f32,
            maxYOut: *mut f32,
            minYOut: *mut f32,
        ),
    pub SetWastedSettings: 
        unsafe extern "C" fn(
            deathTimer: u32,
            fadeTimer: u32,
            fadeInSpeed: f32,
            fadeOutSpeed: f32,
            fadeColour: u32,
            corpseFadeStart: u32,
            corpseFadeTime: u32,
        ),
    pub GetWastedSettings: 
        unsafe extern "C" fn(
            deathTimerOut: *mut u32,
            fadeTimerOut: *mut u32,
            fadeInSpeedOut: *mut f32,
            fadeOutSpeedOut: *mut f32,
            fadeColourOut: *mut u32,
            corpseFadeStartOut: *mut u32,
            corpseFadeTimeOut: *mut u32,
        ),
    pub SetTimeRate: unsafe extern "C" fn(timeRate: i32),
    pub GetTimeRate: unsafe extern "C" fn() -> i32,
    pub SetHour: unsafe extern "C" fn(hour: i32),
    pub GetHour: unsafe extern "C" fn() -> i32,
    pub SetMinute: unsafe extern "C" fn(minute: i32),
    pub GetMinute: unsafe extern "C" fn() -> i32,
    pub SetWeather: unsafe extern "C" fn(weather: i32),
    pub GetWeather: unsafe extern "C" fn() -> i32,
    pub SetGravity: unsafe extern "C" fn(gravity: f32),
    pub GetGravity: unsafe extern "C" fn() -> f32,
    pub SetGameSpeed: unsafe extern "C" fn(gameSpeed: f32),
    pub GetGameSpeed: unsafe extern "C" fn() -> f32,
    pub SetWaterLevel: unsafe extern "C" fn(waterLevel: f32),
    pub GetWaterLevel: unsafe extern "C" fn() -> f32,
    pub SetMaximumFlightAltitude: unsafe extern "C" fn(height: f32),
    pub GetMaximumFlightAltitude: unsafe extern "C" fn() -> f32,
    pub SetKillCommandDelay: unsafe extern "C" fn(delay: i32),
    pub GetKillCommandDelay: unsafe extern "C" fn() -> i32,
    pub SetVehiclesForcedRespawnHeight: unsafe extern "C" fn(height: f32),
    pub GetVehiclesForcedRespawnHeight: unsafe extern "C" fn() -> f32,
    pub CreateExplosion: 
        unsafe extern "C" fn(
            worldId: i32,
            type_: i32,
            x: f32,
            y: f32,
            z: f32,
            responsiblePlayerId: i32,
            atGroundLevel: u8,
        ) -> vcmpError,
    pub PlaySound: 
        unsafe extern "C" fn(worldId: i32, soundId: i32, x: f32, y: f32, z: f32) -> vcmpError,
    pub HideMapObject: 
        unsafe extern "C" fn(modelId: i32, tenthX: i16, tenthY: i16, tenthZ: i16),
    pub ShowMapObject: 
        unsafe extern "C" fn(modelId: i32, tenthX: i16, tenthY: i16, tenthZ: i16),
    pub ShowAllMapObjects: unsafe extern "C" fn(),
    pub SetWeaponDataValue: 
        unsafe extern "C" fn(weaponId: i32, fieldId: i32, value: f64) -> vcmpError,
    pub GetWeaponDataValue:
        unsafe extern "C" fn(weaponId: i32, fieldId: i32) -> f64,
    pub ResetWeaponDataValue:
        unsafe extern "C" fn(weaponId: i32, fieldId: i32) -> vcmpError,
    pub IsWeaponDataValueModified:
        unsafe extern "C" fn(weaponId: i32, fieldId: i32) -> u8,
    pub ResetWeaponData: unsafe extern "C" fn(weaponId: i32) -> vcmpError,
    pub ResetAllWeaponData: unsafe extern "C" fn(),
    pub GetKeyBindUnusedSlot: unsafe extern "C" fn() -> i32,
    pub GetKeyBindData: 
        unsafe extern "C" fn(
            bindId: i32,
            isCalledOnReleaseOut: *mut u8,
            keyOneOut: *mut i32,
            keyTwoOut: *mut i32,
            keyThreeOut: *mut i32,
        ) -> vcmpError,
    pub RegisterKeyBind: 
        unsafe extern "C" fn(
            bindId: i32,
            isCalledOnRelease: u8,
            keyOne: i32,
            keyTwo: i32,
            keyThree: i32,
        ) -> vcmpError,
    pub RemoveKeyBind: unsafe extern "C" fn(bindId: i32) -> vcmpError,
    pub RemoveAllKeyBinds: unsafe extern "C" fn(),
    pub CreateCoordBlip: 
        unsafe extern "C" fn(
            index: i32,
            world: i32,
            x: f32,
            y: f32,
            z: f32,
            scale: i32,
            colour: u32,
            sprite: i32,
        ) -> i32,
    pub DestroyCoordBlip: unsafe extern "C" fn(index: i32) -> vcmpError,
    pub GetCoordBlipInfo: 
        unsafe extern "C" fn(
            index: i32,
            worldOut: *mut i32,
            xOut: *mut f32,
            yOUt: *mut f32,
            zOut: *mut f32,
            scaleOut: *mut i32,
            colourOut: *mut u32,
            spriteOut: *mut i32,
        ) -> vcmpError,
    pub AddRadioStream: 
        unsafe extern "C" fn(
            radioId: i32,
            radioName: *const ::std::os::raw::c_char,
            radioUrl: *const ::std::os::raw::c_char,
            isListed: u8,
        ) -> vcmpError,
    pub RemoveRadioStream: unsafe extern "C" fn(radioId: i32) -> vcmpError,
    pub AddPlayerClass: 
        unsafe extern "C" fn(
            teamId: i32,
            colour: u32,
            modelIndex: i32,
            x: f32,
            y: f32,
            z: f32,
            angle: f32,
            weaponOne: i32,
            weaponOneAmmo: i32,
            weaponTwo: i32,
            weaponTwoAmmo: i32,
            weaponThree: i32,
            weaponThreeAmmo: i32,
        ) -> i32,
    pub SetSpawnPlayerPosition: unsafe extern "C" fn(x: f32, y: f32, z: f32),
    pub SetSpawnCameraPosition: unsafe extern "C" fn(x: f32, y: f32, z: f32),
    pub SetSpawnCameraLookAt: unsafe extern "C" fn(x: f32, y: f32, z: f32),
    pub IsPlayerAdmin: unsafe extern "C" fn(playerId: i32) -> u8,
    pub SetPlayerAdmin:
        unsafe extern "C" fn(playerId: i32, toggle: u8) -> vcmpError,
    pub GetPlayerIP: 
        unsafe extern "C" fn(
            playerId: i32,
            buffer: *mut ::std::os::raw::c_char,
            size: usize,
        ) -> vcmpError,
    pub GetPlayerUID: 
        unsafe extern "C" fn(
            playerId: i32,
            buffer: *mut ::std::os::raw::c_char,
            size: usize,
        ) -> vcmpError,
    pub GetPlayerUID2: 
        unsafe extern "C" fn(
            playerId: i32,
            buffer: *mut ::std::os::raw::c_char,
            size: usize,
        ) -> vcmpError,
    pub KickPlayer: unsafe extern "C" fn(playerId: i32) -> vcmpError,
    pub BanPlayer: unsafe extern "C" fn(playerId: i32) -> vcmpError,
    pub BanIP: unsafe extern "C" fn(ipAddress: *mut ::std::os::raw::c_char),
    pub UnbanIP:
        unsafe extern "C" fn(ipAddress: *mut ::std::os::raw::c_char) -> u8,
    pub IsIPBanned:
        unsafe extern "C" fn(ipAddress: *mut ::std::os::raw::c_char) -> u8,
    pub GetPlayerIdFromName:
        unsafe extern "C" fn(name: *const ::std::os::raw::c_char) -> i32,
    pub IsPlayerConnected: unsafe extern "C" fn(playerId: i32) -> u8,
    pub IsPlayerStreamedForPlayer:
        unsafe extern "C" fn(checkedPlayerId: i32, playerId: i32) -> u8,
    pub GetPlayerKey: unsafe extern "C" fn(playerId: i32) -> u32,
    pub GetPlayerName: 
        unsafe extern "C" fn(
            playerId: i32,
            buffer: *mut ::std::os::raw::c_char,
            size: usize,
        ) -> vcmpError,
    pub SetPlayerName: 
        unsafe extern "C" fn(playerId: i32, name: *const ::std::os::raw::c_char) -> vcmpError,
    pub GetPlayerState:
        unsafe extern "C" fn(playerId: i32) -> vcmpPlayerState,
    pub SetPlayerOption: 
        unsafe extern "C" fn(playerId: i32, option: vcmpPlayerOption, toggle: u8) -> vcmpError,
    pub GetPlayerOption:
        unsafe extern "C" fn(playerId: i32, option: vcmpPlayerOption) -> u8,
    pub SetPlayerWorld:
        unsafe extern "C" fn(playerId: i32, world: i32) -> vcmpError,
    pub GetPlayerWorld: unsafe extern "C" fn(playerId: i32) -> i32,
    pub SetPlayerSecondaryWorld: 
        unsafe extern "C" fn(playerId: i32, secondaryWorld: i32) -> vcmpError,
    pub GetPlayerSecondaryWorld: unsafe extern "C" fn(playerId: i32) -> i32,
    pub GetPlayerUniqueWorld: unsafe extern "C" fn(playerId: i32) -> i32,
    pub IsPlayerWorldCompatible:
        unsafe extern "C" fn(playerId: i32, world: i32) -> u8,
    pub GetPlayerClass: unsafe extern "C" fn(playerId: i32) -> i32,
    pub SetPlayerTeam:
        unsafe extern "C" fn(playerId: i32, teamId: i32) -> vcmpError,
    pub GetPlayerTeam: unsafe extern "C" fn(playerId: i32) -> i32,
    pub SetPlayerSkin:
        unsafe extern "C" fn(playerId: i32, skinId: i32) -> vcmpError,
    pub GetPlayerSkin: unsafe extern "C" fn(playerId: i32) -> i32,
    pub SetPlayerColour:
        unsafe extern "C" fn(playerId: i32, colour: u32) -> vcmpError,
    pub GetPlayerColour: unsafe extern "C" fn(playerId: i32) -> u32,
    pub IsPlayerSpawned: unsafe extern "C" fn(playerId: i32) -> u8,
    pub ForcePlayerSpawn: unsafe extern "C" fn(playerId: i32) -> vcmpError,
    pub ForcePlayerSelect: unsafe extern "C" fn(playerId: i32) -> vcmpError,
    pub ForceAllSelect: unsafe extern "C" fn(),
    pub IsPlayerTyping: unsafe extern "C" fn(playerId: i32) -> u8,
    pub GivePlayerMoney:
        unsafe extern "C" fn(playerId: i32, amount: i32) -> vcmpError,
    pub SetPlayerMoney:
        unsafe extern "C" fn(playerId: i32, amount: i32) -> vcmpError,
    pub GetPlayerMoney: unsafe extern "C" fn(playerId: i32) -> i32,
    pub SetPlayerScore:
        unsafe extern "C" fn(playerId: i32, score: i32) -> vcmpError,
    pub GetPlayerScore: unsafe extern "C" fn(playerId: i32) -> i32,
    pub SetPlayerWantedLevel:
        unsafe extern "C" fn(playerId: i32, level: i32) -> vcmpError,
    pub GetPlayerWantedLevel: unsafe extern "C" fn(playerId: i32) -> i32,
    pub GetPlayerPing: unsafe extern "C" fn(playerId: i32) -> i32,
    pub GetPlayerFPS: unsafe extern "C" fn(playerId: i32) -> f64,
    pub SetPlayerHealth:
        unsafe extern "C" fn(playerId: i32, health: f32) -> vcmpError,
    pub GetPlayerHealth: unsafe extern "C" fn(playerId: i32) -> f32,
    pub SetPlayerArmour:
        unsafe extern "C" fn(playerId: i32, armour: f32) -> vcmpError,
    pub GetPlayerArmour: unsafe extern "C" fn(playerId: i32) -> f32,
    pub SetPlayerImmunityFlags:
        unsafe extern "C" fn(playerId: i32, flags: u32) -> vcmpError,
    pub GetPlayerImmunityFlags: unsafe extern "C" fn(playerId: i32) -> u32,
    pub SetPlayerPosition: 
        unsafe extern "C" fn(playerId: i32, x: f32, y: f32, z: f32) -> vcmpError,
    pub GetPlayerPosition: 
        unsafe extern "C" fn(
            playerId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub SetPlayerSpeed: 
        unsafe extern "C" fn(playerId: i32, x: f32, y: f32, z: f32) -> vcmpError,
    pub GetPlayerSpeed: 
        unsafe extern "C" fn(
            playerId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub AddPlayerSpeed: 
        unsafe extern "C" fn(playerId: i32, x: f32, y: f32, z: f32) -> vcmpError,
    pub SetPlayerHeading:
        unsafe extern "C" fn(playerId: i32, angle: f32) -> vcmpError,
    pub GetPlayerHeading: unsafe extern "C" fn(playerId: i32) -> f32,
    pub SetPlayerAlpha: 
        unsafe extern "C" fn(playerId: i32, alpha: i32, fadeTime: u32) -> vcmpError,
    pub GetPlayerAlpha: unsafe extern "C" fn(playerId: i32) -> i32,
    pub GetPlayerAimPosition: 
        unsafe extern "C" fn(
            playerId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub GetPlayerAimDirection: 
        unsafe extern "C" fn(
            playerId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub IsPlayerOnFire: unsafe extern "C" fn(playerId: i32) -> u8,
    pub IsPlayerCrouching: unsafe extern "C" fn(playerId: i32) -> u8,
    pub GetPlayerAction: unsafe extern "C" fn(playerId: i32) -> i32,
    pub GetPlayerGameKeys: unsafe extern "C" fn(playerId: i32) -> u32,
    pub PutPlayerInVehicle: 
        unsafe extern "C" fn(
            playerId: i32,
            vehicleId: i32,
            slotIndex: i32,
            makeRoom: u8,
            warp: u8,
        ) -> vcmpError,
    pub RemovePlayerFromVehicle:
        unsafe extern "C" fn(playerId: i32) -> vcmpError,
    pub GetPlayerInVehicleStatus:
        unsafe extern "C" fn(playerId: i32) -> vcmpPlayerVehicle,
    pub GetPlayerInVehicleSlot: unsafe extern "C" fn(playerId: i32) -> i32,
    pub GetPlayerVehicleId: unsafe extern "C" fn(playerId: i32) -> i32,
    pub GivePlayerWeapon: 
        unsafe extern "C" fn(playerId: i32, weaponId: i32, ammo: i32) -> vcmpError,
    pub SetPlayerWeapon: 
        unsafe extern "C" fn(playerId: i32, weaponId: i32, ammo: i32) -> vcmpError,
    pub GetPlayerWeapon: unsafe extern "C" fn(playerId: i32) -> i32,
    pub GetPlayerWeaponAmmo: unsafe extern "C" fn(playerId: i32) -> i32,
    pub SetPlayerWeaponSlot:
        unsafe extern "C" fn(playerId: i32, slot: i32) -> vcmpError,
    pub GetPlayerWeaponSlot: unsafe extern "C" fn(playerId: i32) -> i32,
    pub GetPlayerWeaponAtSlot:
        unsafe extern "C" fn(playerId: i32, slot: i32) -> i32,
    pub GetPlayerAmmoAtSlot:
        unsafe extern "C" fn(playerId: i32, slot: i32) -> i32,
    pub RemovePlayerWeapon:
        unsafe extern "C" fn(playerId: i32, weaponId: i32) -> vcmpError,
    pub RemoveAllWeapons: unsafe extern "C" fn(playerId: i32) -> vcmpError,
    pub SetCameraPosition: 
        unsafe extern "C" fn(
            playerId: i32,
            posX: f32,
            posY: f32,
            posZ: f32,
            lookX: f32,
            lookY: f32,
            lookZ: f32,
        ) -> vcmpError,
    pub RestoreCamera: unsafe extern "C" fn(playerId: i32) -> vcmpError,
    pub IsCameraLocked: unsafe extern "C" fn(playerId: i32) -> u8,
    pub SetPlayerAnimation: 
        unsafe extern "C" fn(playerId: i32, groupId: i32, animationId: i32) -> vcmpError,
    pub GetPlayerStandingOnVehicle:
        unsafe extern "C" fn(playerId: i32) -> i32,
    pub GetPlayerStandingOnObject:
        unsafe extern "C" fn(playerId: i32) -> i32,
    pub IsPlayerAway: unsafe extern "C" fn(playerId: i32) -> u8,
    pub GetPlayerSpectateTarget: unsafe extern "C" fn(playerId: i32) -> i32,
    pub SetPlayerSpectateTarget:
        unsafe extern "C" fn(playerId: i32, targetId: i32) -> vcmpError,
    pub RedirectPlayerToServer: 
        unsafe extern "C" fn(
            playerId: i32,
            ip: *const ::std::os::raw::c_char,
            port: u32,
            nick: *const ::std::os::raw::c_char,
            serverPassword: *const ::std::os::raw::c_char,
            userPassword: *const ::std::os::raw::c_char,
        ) -> vcmpError,
    pub CheckEntityExists:
        unsafe extern "C" fn(entityPool: vcmpEntityPool, index: i32) -> u8,
    pub CreateVehicle: 
        unsafe extern "C" fn(
            modelIndex: i32,
            world: i32,
            x: f32,
            y: f32,
            z: f32,
            angle: f32,
            primaryColour: i32,
            secondaryColour: i32,
        ) -> i32,
    pub DeleteVehicle: unsafe extern "C" fn(vehicleId: i32) -> vcmpError,
    pub SetVehicleOption: 
        unsafe extern "C" fn(vehicleId: i32, option: vcmpVehicleOption, toggle: u8) -> vcmpError,
    pub GetVehicleOption: 
        unsafe extern "C" fn(vehicleId: i32, option: vcmpVehicleOption) -> u8,
    pub GetVehicleSyncSource: unsafe extern "C" fn(vehicleId: i32) -> i32,
    pub GetVehicleSyncType:
        unsafe extern "C" fn(vehicleId: i32) -> vcmpVehicleSync,
    pub IsVehicleStreamedForPlayer:
        unsafe extern "C" fn(vehicleId: i32, playerId: i32) -> u8,
    pub SetVehicleWorld:
        unsafe extern "C" fn(vehicleId: i32, world: i32) -> vcmpError,
    pub GetVehicleWorld: unsafe extern "C" fn(vehicleId: i32) -> i32,
    pub GetVehicleModel: unsafe extern "C" fn(vehicleId: i32) -> i32,
    pub GetVehicleOccupant:
        unsafe extern "C" fn(vehicleId: i32, slotIndex: i32) -> i32,
    pub RespawnVehicle: unsafe extern "C" fn(vehicleId: i32) -> vcmpError,
    pub SetVehicleImmunityFlags: 
        unsafe extern "C" fn(vehicleId: i32, immunityFlags: u32) -> vcmpError,
    pub GetVehicleImmunityFlags: unsafe extern "C" fn(vehicleId: i32) -> u32,
    pub ExplodeVehicle: unsafe extern "C" fn(vehicleId: i32) -> vcmpError,
    pub IsVehicleWrecked: unsafe extern "C" fn(vehicleId: i32) -> u8,
    pub SetVehiclePosition: 
        unsafe extern "C" fn(
            vehicleId: i32,
            x: f32,
            y: f32,
            z: f32,
            removeOccupants: u8,
        ) -> vcmpError,
    pub GetVehiclePosition: 
        unsafe extern "C" fn(
            vehicleId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub SetVehicleRotation: 
        unsafe extern "C" fn(vehicleId: i32, x: f32, y: f32, z: f32, w: f32) -> vcmpError,
    pub SetVehicleRotationEuler: 
        unsafe extern "C" fn(vehicleId: i32, x: f32, y: f32, z: f32) -> vcmpError,
    pub GetVehicleRotation: 
        unsafe extern "C" fn(
            vehicleId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
            wOut: *mut f32,
        ) -> vcmpError,
    pub GetVehicleRotationEuler: 
        unsafe extern "C" fn(
            vehicleId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub SetVehicleSpeed: 
        unsafe extern "C" fn(
            vehicleId: i32,
            x: f32,
            y: f32,
            z: f32,
            add: u8,
            relative: u8,
        ) -> vcmpError,
    pub GetVehicleSpeed: 
        unsafe extern "C" fn(
            vehicleId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
            relative: u8,
        ) -> vcmpError,
    pub SetVehicleTurnSpeed: 
        unsafe extern "C" fn(
            vehicleId: i32,
            x: f32,
            y: f32,
            z: f32,
            add: u8,
            relative: u8,
        ) -> vcmpError,
    pub GetVehicleTurnSpeed: 
        unsafe extern "C" fn(
            vehicleId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
            relative: u8,
        ) -> vcmpError,
    pub SetVehicleSpawnPosition: 
        unsafe extern "C" fn(vehicleId: i32, x: f32, y: f32, z: f32) -> vcmpError,
    pub GetVehicleSpawnPosition: 
        unsafe extern "C" fn(
            vehicleId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub SetVehicleSpawnRotation: 
        unsafe extern "C" fn(vehicleId: i32, x: f32, y: f32, z: f32, w: f32) -> vcmpError,
    pub SetVehicleSpawnRotationEuler: 
        unsafe extern "C" fn(vehicleId: i32, x: f32, y: f32, z: f32) -> vcmpError,
    pub GetVehicleSpawnRotation: 
        unsafe extern "C" fn(
            vehicleId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
            wOut: *mut f32,
        ) -> vcmpError,
    pub GetVehicleSpawnRotationEuler: 
        unsafe extern "C" fn(
            vehicleId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub SetVehicleIdleRespawnTimer:
        unsafe extern "C" fn(vehicleId: i32, millis: u32) -> vcmpError,
    pub GetVehicleIdleRespawnTimer:
        unsafe extern "C" fn(vehicleId: i32) -> u32,
    pub SetVehicleHealth:
        unsafe extern "C" fn(vehicleId: i32, health: f32) -> vcmpError,
    pub GetVehicleHealth: unsafe extern "C" fn(vehicleId: i32) -> f32,
    pub SetVehicleColour: 
        unsafe extern "C" fn(vehicleId: i32, primaryColour: i32, secondaryColour: i32) -> vcmpError,
    pub GetVehicleColour: 
        unsafe extern "C" fn(
            vehicleId: i32,
            primaryColourOut: *mut i32,
            secondaryColourOut: *mut i32,
        ) -> vcmpError,
    pub SetVehiclePartStatus: 
        unsafe extern "C" fn(vehicleId: i32, partId: i32, status: i32) -> vcmpError,
    pub GetVehiclePartStatus:
        unsafe extern "C" fn(vehicleId: i32, partId: i32) -> i32,
    pub SetVehicleTyreStatus: 
        unsafe extern "C" fn(vehicleId: i32, tyreId: i32, status: i32) -> vcmpError,
    pub GetVehicleTyreStatus:
        unsafe extern "C" fn(vehicleId: i32, tyreId: i32) -> i32,
    pub SetVehicleDamageData:
        unsafe extern "C" fn(vehicleId: i32, damageData: u32) -> vcmpError,
    pub GetVehicleDamageData: unsafe extern "C" fn(vehicleId: i32) -> u32,
    pub SetVehicleRadio:
        unsafe extern "C" fn(vehicleId: i32, radioId: i32) -> vcmpError,
    pub GetVehicleRadio: unsafe extern "C" fn(vehicleId: i32) -> i32,
    pub GetVehicleTurretRotation: 
        unsafe extern "C" fn(
            vehicleId: i32,
            horizontalOut: *mut f32,
            verticalOut: *mut f32,
        ) -> vcmpError,
    pub ResetAllVehicleHandlings: unsafe extern "C" fn(),
    pub ExistsHandlingRule:
        unsafe extern "C" fn(modelIndex: i32, ruleIndex: i32) -> u8,
    pub SetHandlingRule: 
        unsafe extern "C" fn(modelIndex: i32, ruleIndex: i32, value: f64) -> vcmpError,
    pub GetHandlingRule:
        unsafe extern "C" fn(modelIndex: i32, ruleIndex: i32) -> f64,
    pub ResetHandlingRule:
        unsafe extern "C" fn(modelIndex: i32, ruleIndex: i32) -> vcmpError,
    pub ResetHandling: unsafe extern "C" fn(modelIndex: i32) -> vcmpError,
    pub ExistsInstHandlingRule:
        unsafe extern "C" fn(vehicleId: i32, ruleIndex: i32) -> u8,
    pub SetInstHandlingRule: 
        unsafe extern "C" fn(vehicleId: i32, ruleIndex: i32, value: f64) -> vcmpError,
    pub GetInstHandlingRule:
        unsafe extern "C" fn(vehicleId: i32, ruleIndex: i32) -> f64,
    pub ResetInstHandlingRule:
        unsafe extern "C" fn(vehicleId: i32, ruleIndex: i32) -> vcmpError,
    pub ResetInstHandling: unsafe extern "C" fn(vehicleId: i32) -> vcmpError,
    pub CreatePickup: 
        unsafe extern "C" fn(
            modelIndex: i32,
            world: i32,
            quantity: i32,
            x: f32,
            y: f32,
            z: f32,
            alpha: i32,
            isAutomatic: u8,
        ) -> i32,
    pub DeletePickup: unsafe extern "C" fn(pickupId: i32) -> vcmpError,
    pub IsPickupStreamedForPlayer:
        unsafe extern "C" fn(pickupId: i32, playerId: i32) -> u8,
    pub SetPickupWorld:
        unsafe extern "C" fn(pickupId: i32, world: i32) -> vcmpError,
    pub GetPickupWorld: unsafe extern "C" fn(pickupId: i32) -> i32,
    pub SetPickupAlpha:
        unsafe extern "C" fn(pickupId: i32, alpha: i32) -> vcmpError,
    pub GetPickupAlpha: unsafe extern "C" fn(pickupId: i32) -> i32,
    pub SetPickupIsAutomatic:
        unsafe extern "C" fn(pickupId: i32, toggle: u8) -> vcmpError,
    pub IsPickupAutomatic: unsafe extern "C" fn(pickupId: i32) -> u8,
    pub SetPickupAutoTimer: 
        unsafe extern "C" fn(pickupId: i32, durationMillis: u32) -> vcmpError,
    pub GetPickupAutoTimer: unsafe extern "C" fn(pickupId: i32) -> u32,
    pub RefreshPickup: unsafe extern "C" fn(pickupId: i32) -> vcmpError,
    pub SetPickupPosition: 
        unsafe extern "C" fn(pickupId: i32, x: f32, y: f32, z: f32) -> vcmpError,
    pub GetPickupPosition: 
        unsafe extern "C" fn(
            pickupId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub GetPickupModel: unsafe extern "C" fn(pickupId: i32) -> i32,
    pub GetPickupQuantity: unsafe extern "C" fn(pickupId: i32) -> i32,
    pub CreateCheckPoint: 
        unsafe extern "C" fn(
            playerId: i32,
            world: i32,
            isSphere: u8,
            x: f32,
            y: f32,
            z: f32,
            red: i32,
            green: i32,
            blue: i32,
            alpha: i32,
            radius: f32,
        ) -> i32,
    pub DeleteCheckPoint:
        unsafe extern "C" fn(checkPointId: i32) -> vcmpError,
    pub IsCheckPointStreamedForPlayer:
        unsafe extern "C" fn(checkPointId: i32, playerId: i32) -> u8,
    pub IsCheckPointSphere: unsafe extern "C" fn(checkPointId: i32) -> u8,
    pub SetCheckPointWorld:
        unsafe extern "C" fn(checkPointId: i32, world: i32) -> vcmpError,
    pub GetCheckPointWorld: unsafe extern "C" fn(checkPointId: i32) -> i32,
    pub SetCheckPointColour: 
        unsafe extern "C" fn(
            checkPointId: i32,
            red: i32,
            green: i32,
            blue: i32,
            alpha: i32,
        ) -> vcmpError,
    pub GetCheckPointColour: 
        unsafe extern "C" fn(
            checkPointId: i32,
            redOut: *mut i32,
            greenOut: *mut i32,
            blueOut: *mut i32,
            alphaOut: *mut i32,
        ) -> vcmpError,
    pub SetCheckPointPosition: 
        unsafe extern "C" fn(checkPointId: i32, x: f32, y: f32, z: f32) -> vcmpError,
    pub GetCheckPointPosition: 
        unsafe extern "C" fn(
            checkPointId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub SetCheckPointRadius:
        unsafe extern "C" fn(checkPointId: i32, radius: f32) -> vcmpError,
    pub GetCheckPointRadius: unsafe extern "C" fn(checkPointId: i32) -> f32,
    pub GetCheckPointOwner: unsafe extern "C" fn(checkPointId: i32) -> i32,
    pub CreateObject: 
        unsafe extern "C" fn(
            modelIndex: i32,
            world: i32,
            x: f32,
            y: f32,
            z: f32,
            alpha: i32,
        ) -> i32,
    pub DeleteObject: unsafe extern "C" fn(objectId: i32) -> vcmpError,
    pub IsObjectStreamedForPlayer:
        unsafe extern "C" fn(objectId: i32, playerId: i32) -> u8,
    pub GetObjectModel: unsafe extern "C" fn(objectId: i32) -> i32,
    pub SetObjectWorld:
        unsafe extern "C" fn(objectId: i32, world: i32) -> vcmpError,
    pub GetObjectWorld: unsafe extern "C" fn(objectId: i32) -> i32,
    pub SetObjectAlpha: 
        unsafe extern "C" fn(objectId: i32, alpha: i32, duration: u32) -> vcmpError,
    pub GetObjectAlpha: unsafe extern "C" fn(objectId: i32) -> i32,
    pub MoveObjectTo: 
        unsafe extern "C" fn(objectId: i32, x: f32, y: f32, z: f32, duration: u32) -> vcmpError,
    pub MoveObjectBy: 
        unsafe extern "C" fn(objectId: i32, x: f32, y: f32, z: f32, duration: u32) -> vcmpError,
    pub SetObjectPosition: 
        unsafe extern "C" fn(objectId: i32, x: f32, y: f32, z: f32) -> vcmpError,
    pub GetObjectPosition: 
        unsafe extern "C" fn(
            objectId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub RotateObjectTo: 
        unsafe extern "C" fn(
            objectId: i32,
            x: f32,
            y: f32,
            z: f32,
            w: f32,
            duration: u32,
        ) -> vcmpError,
    pub RotateObjectToEuler: 
        unsafe extern "C" fn(objectId: i32, x: f32, y: f32, z: f32, duration: u32) -> vcmpError,
    pub RotateObjectBy: 
        unsafe extern "C" fn(
            objectId: i32,
            x: f32,
            y: f32,
            z: f32,
            w: f32,
            duration: u32,
        ) -> vcmpError,
    pub RotateObjectByEuler: 
        unsafe extern "C" fn(objectId: i32, x: f32, y: f32, z: f32, duration: u32) -> vcmpError,
    pub GetObjectRotation: 
        unsafe extern "C" fn(
            objectId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
            wOut: *mut f32,
        ) -> vcmpError,
    pub GetObjectRotationEuler: 
        unsafe extern "C" fn(
            objectId: i32,
            xOut: *mut f32,
            yOut: *mut f32,
            zOut: *mut f32,
        ) -> vcmpError,
    pub SetObjectShotReportEnabled:
        unsafe extern "C" fn(objectId: i32, toggle: u8) -> vcmpError,
    pub IsObjectShotReportEnabled: unsafe extern "C" fn(objectId: i32) -> u8,
    pub SetObjectTouchedReportEnabled:
        unsafe extern "C" fn(objectId: i32, toggle: u8) -> vcmpError,
    pub IsObjectTouchedReportEnabled:
        unsafe extern "C" fn(objectId: i32) -> u8,
    pub GetPlayerModuleList:
        unsafe extern "C" fn(playerId: i32) -> vcmpError,
    pub SetPickupOption: 
        unsafe extern "C" fn(pickupId: i32, option: vcmpPickupOption, toggle: u8) -> vcmpError,
    pub GetPickupOption:
        unsafe extern "C" fn(pickupId: i32, option: vcmpPickupOption) -> u8,
    pub SetFallTimer: unsafe extern "C" fn(timeRate: u16),
    pub GetFallTimer: unsafe extern "C" fn() -> u16,
    pub SetVehicleLightsData:
        unsafe extern "C" fn(vehicleId: i32, lightsData: u32) -> vcmpError,
    pub GetVehicleLightsData: unsafe extern "C" fn(vehicleId: i32) -> u32,
    pub KillPlayer: unsafe extern "C" fn(playerId: i32) -> vcmpError,
    pub SetVehicle3DArrowForPlayer: 
        unsafe extern "C" fn(vehicleId: i32, targetPlayerId: i32, isEnabled: u8) -> vcmpError,
    pub GetVehicle3DArrowForPlayer:
        unsafe extern "C" fn(vehicleId: i32, targetPlayerId: i32) -> u8,
    pub SetPlayer3DArrowForPlayer: 
        unsafe extern "C" fn(playerId: i32, targetPlayerId: i32, isEnabled: u8) -> vcmpError,
    pub GetPlayer3DArrowForPlayer:
        unsafe extern "C" fn(playerId: i32, targetPlayerId: i32) -> u8,
    pub SetPlayerDrunkHandling:
        unsafe extern "C" fn(playerId: i32, drunkLevel: u32) -> vcmpError,
    pub GetPlayerDrunkHandling: unsafe extern "C" fn(playerId: i32) -> u32,
    pub SetPlayerDrunkVisuals:
        unsafe extern "C" fn(playerId: i32, drunkLevel: u8) -> vcmpError,
    pub GetPlayerDrunkVisuals: unsafe extern "C" fn(playerId: i32) -> u8,
    pub InterpolateCameraLookAt: 
        unsafe extern "C" fn(
            playerId: i32,
            lookX: f32,
            lookY: f32,
            lookZ: f32,
            interpTimeMS: u32,
        ) -> vcmpError,
    pub GetNetworkStatistics: 
        unsafe extern "C" fn(playerId: i32, option: vcmpNetworkStatisticsOption) -> f64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PluginCallbacks {
    pub structSize: u32,
    pub OnServerInitialise: ::std::option::Option<unsafe extern "C" fn() -> u8>,
    pub OnServerShutdown: ::std::option::Option<unsafe extern "C" fn()>,
    pub OnServerFrame: ::std::option::Option<unsafe extern "C" fn(elapsedTime: f32)>,
    pub OnPluginCommand: ::std::option::Option<
        unsafe extern "C" fn(commandIdentifier: u32, message: *const ::std::os::raw::c_char) -> u8,
    >,
    pub OnIncomingConnection: ::std::option::Option<
        unsafe extern "C" fn(
            playerName: *mut ::std::os::raw::c_char,
            nameBufferSize: usize,
            userPassword: *const ::std::os::raw::c_char,
            ipAddress: *const ::std::os::raw::c_char,
        ) -> u8,
    >,
    pub OnClientScriptData:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, data: *const u8, size: usize)>,
    pub OnPlayerConnect: ::std::option::Option<unsafe extern "C" fn(playerId: i32)>,
    pub OnPlayerDisconnect:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, reason: vcmpDisconnectReason)>,
    pub OnPlayerRequestClass:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, offset: i32) -> u8>,
    pub OnPlayerRequestSpawn: ::std::option::Option<unsafe extern "C" fn(playerId: i32) -> u8>,
    pub OnPlayerSpawn: ::std::option::Option<unsafe extern "C" fn(playerId: i32)>,
    pub OnPlayerDeath: ::std::option::Option<
        unsafe extern "C" fn(playerId: i32, killerId: i32, reason: i32, bodyPart: vcmpBodyPart),
    >,
    pub OnPlayerUpdate:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, updateType: vcmpPlayerUpdate)>,
    pub OnPlayerRequestEnterVehicle: ::std::option::Option<
        unsafe extern "C" fn(playerId: i32, vehicleId: i32, slotIndex: i32) -> u8,
    >,
    pub OnPlayerEnterVehicle:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, vehicleId: i32, slotIndex: i32)>,
    pub OnPlayerExitVehicle:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, vehicleId: i32)>,
    pub OnPlayerNameChange: ::std::option::Option<
        unsafe extern "C" fn(
            playerId: i32,
            oldName: *const ::std::os::raw::c_char,
            newName: *const ::std::os::raw::c_char,
        ),
    >,
    pub OnPlayerStateChange: ::std::option::Option<
        unsafe extern "C" fn(playerId: i32, oldState: vcmpPlayerState, newState: vcmpPlayerState),
    >,
    pub OnPlayerActionChange:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, oldAction: i32, newAction: i32)>,
    pub OnPlayerOnFireChange:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, isOnFire: u8)>,
    pub OnPlayerCrouchChange:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, isCrouching: u8)>,
    pub OnPlayerGameKeysChange:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, oldKeys: u32, newKeys: u32)>,
    pub OnPlayerBeginTyping: ::std::option::Option<unsafe extern "C" fn(playerId: i32)>,
    pub OnPlayerEndTyping: ::std::option::Option<unsafe extern "C" fn(playerId: i32)>,
    pub OnPlayerAwayChange: ::std::option::Option<unsafe extern "C" fn(playerId: i32, isAway: u8)>,
    pub OnPlayerMessage: ::std::option::Option<
        unsafe extern "C" fn(playerId: i32, message: *const ::std::os::raw::c_char) -> u8,
    >,
    pub OnPlayerCommand: ::std::option::Option<
        unsafe extern "C" fn(playerId: i32, message: *const ::std::os::raw::c_char) -> u8,
    >,
    pub OnPlayerPrivateMessage: ::std::option::Option<
        unsafe extern "C" fn(
            playerId: i32,
            targetPlayerId: i32,
            message: *const ::std::os::raw::c_char,
        ) -> u8,
    >,
    pub OnPlayerKeyBindDown:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, bindId: i32)>,
    pub OnPlayerKeyBindUp: ::std::option::Option<unsafe extern "C" fn(playerId: i32, bindId: i32)>,
    pub OnPlayerSpectate:
        ::std::option::Option<unsafe extern "C" fn(playerId: i32, targetPlayerId: i32)>,
    pub OnPlayerCrashReport: ::std::option::Option<
        unsafe extern "C" fn(playerId: i32, report: *const ::std::os::raw::c_char),
    >,
    pub OnVehicleUpdate:
        ::std::option::Option<unsafe extern "C" fn(vehicleId: i32, updateType: vcmpVehicleUpdate)>,
    pub OnVehicleExplode: ::std::option::Option<unsafe extern "C" fn(vehicleId: i32)>,
    pub OnVehicleRespawn: ::std::option::Option<unsafe extern "C" fn(vehicleId: i32)>,
    pub OnObjectShot:
        ::std::option::Option<unsafe extern "C" fn(objectId: i32, playerId: i32, weaponId: i32)>,
    pub OnObjectTouched: ::std::option::Option<unsafe extern "C" fn(objectId: i32, playerId: i32)>,
    pub OnPickupPickAttempt:
        ::std::option::Option<unsafe extern "C" fn(pickupId: i32, playerId: i32) -> u8>,
    pub OnPickupPicked: ::std::option::Option<unsafe extern "C" fn(pickupId: i32, playerId: i32)>,
    pub OnPickupRespawn: ::std::option::Option<unsafe extern "C" fn(pickupId: i32)>,
    pub OnCheckpointEntered:
        ::std::option::Option<unsafe extern "C" fn(checkPointId: i32, playerId: i32)>,
    pub OnCheckpointExited:
        ::std::option::Option<unsafe extern "C" fn(checkPointId: i32, playerId: i32)>,
    pub OnEntityPoolChange: ::std::option::Option<
        unsafe extern "C" fn(entityType: vcmpEntityPool, entityId: i32, isDeleted: u8),
    >,
    pub OnServerPerformanceReport: ::std::option::Option<
        unsafe extern "C" fn(
            entryCount: usize,
            descriptions: *mut *const ::std::os::raw::c_char,
            times: *mut u64,
        ),
    >,
    pub OnPlayerModuleList: ::std::option::Option<
        unsafe extern "C" fn(playerId: i32, list: *const ::std::os::raw::c_char),
    >,
    pub OnEntityStreamingChange: ::std::option::Option<
        unsafe extern "C" fn(
            playerId: i32,
            entityId: i32,
            entityType: vcmpEntityPool,
            isDeleted: u8,
        ),
    >,
}
