# 复合动作：构建并推送Docker镜像
name: "Build and Push Docker"
description: "Build Docker image and push to Docker Hub"

inputs:
  tags:
    description: "Docker标签（逗号分隔）"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ inputs.tags }}
        platforms: linux/amd64