from .abc import Event

class ServerEvent(Event):
    ...

class ServerInitialiseEvent(ServerEvent):
    ...

class ServerShutdownEvent(ServerEvent):
    ...

class ServerFrameEvent(ServerEvent):
    @property
    def elapsed_time(self) -> float: ...

class ServerPerformanceReportEvent(ServerEvent):
    @property
    def entry_count(self) -> int: ...
    @property
    def descriptions(self) -> list[str]: ...
    @property
    def times(self) -> list[int]: ...
