from .abc import Event

class PlayerEvent(Event):
    ...

class IncomingConnectionEvent(PlayerEvent):
    ...

class ClientScriptDataEvent(PlayerEvent):
    ...

class PlayerConnectEvent(PlayerEvent):
    ...

class PlayerDisconnectEvent(PlayerEvent):
    ...

class PlayerRequestClassEvent(PlayerEvent):
    ...

class PlayerRequestSpawnEvent(PlayerEvent):
    ...

class PlayerSpawnEvent(PlayerEvent):
    ...

class PlayerDeathEvent(PlayerEvent):
    ...

class PlayerUpdateEvent(PlayerEvent):
    ...

class PlayerRequestEnterVehicleEvent(PlayerEvent):
    ...

class PlayerEnterVehicleEvent(PlayerEvent):
    ...

class PlayerExitVehicleEvent(PlayerEvent):
    ...

class PlayerNameChangeEvent(PlayerEvent):
    ...

class PlayerStateChangeEvent(PlayerEvent):
    ...

class PlayerActionChangeEvent(PlayerEvent):
    ...

class PlayerOnFireChangeEvent(PlayerEvent):
    ...

class PlayerCrouchChangeEvent(PlayerEvent):
    ...

class PlayerGameKeysChangeEvent(PlayerEvent):
    ...

class PlayerBeginTypingEvent(PlayerEvent):
    ...

class PlayerEndTypingEvent(PlayerEvent):
    ...

class PlayerAwayChangeEvent(PlayerEvent):
    ...

class PlayerMessageEvent(PlayerEvent):
    ...

class PlayerCommandEvent(PlayerEvent):
    ...

class PlayerPrivateMessageEvent(PlayerEvent):
    ...

class PlayerKeyBindDownEvent(PlayerEvent):
    ...

class PlayerKeyBindUpEvent(PlayerEvent):
    ...

class PlayerSpectateEvent(PlayerEvent):
    ...

class PlayerCrashReportEvent(PlayerEvent):
    ...

