from .abc import Event

class VehicleEvent(Event):
    ...

class VehicleUpdateEvent(VehicleEvent):
    ...

class VehicleExplodeEvent(VehicleEvent):
    ...

class VehicleRespawnEvent(VehicleEvent):
    ...