[package]
name = "squirrel_ffi_macros"
version = "0.2.0"
edition = "2024"
authors = [
    "tianxiu2b2t <administrator@ttb-network.top>",
]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"