from typing import Optional

from vcmp.types import RGB, Vector, WastedSettings

def set_taxi_boost_jump(toggle: bool) -> None: ...
def get_taxi_boost_jump() -> bool: ...

def set_drive_on_water(toggle: bool) -> None: ...
def get_drive_on_water() -> bool: ...

def set_fast_switch(toggle: bool) -> None: ...
def get_fast_switch() -> bool: ...

def set_friendly_fire(toggle: bool) -> None: ...
def get_friendly_fire() -> bool: ...

def set_disable_drive_by(toggle: bool) -> None: ...
def get_disable_drive_by() -> bool: ...

def set_perfect_handling(toggle: bool) -> None: ...
def get_perfect_handling() -> bool: ...

def set_flying_cars(toggle: bool) -> None: ...
def get_flying_cars() -> bool: ...

def set_jump_switch(toggle: bool) -> None: ...
def get_jump_switch() -> bool: ...

def set_show_markers(toggle: bool) -> None: ...
def get_show_markers() -> bool: ...

def set_only_show_team_markers(toggle: bool) -> None: ...
def get_only_show_team_markers() -> bool: ...

def set_stunt_bike(toggle: bool) -> None: ...
def get_stunt_bike() -> bool: ...

def set_shoot_in_air(toggle: bool) -> None: ...
def get_shoot_in_air() -> bool: ...

def set_show_name_tags(toggle: bool) -> None: ...
def get_show_name_tags() -> bool: ...

def set_join_messages(toggle: bool) -> None: ...
def get_join_messages() -> bool: ...

def set_death_messages(toggle: bool) -> None: ...
def get_death_messages() -> bool: ...

def set_chat_tags_enabled(toggle: bool) -> None: ...
def get_chat_tags_enabled() -> bool: ...

def set_use_classes(toggle: bool) -> None: ...
def get_use_classes() -> bool: ...

def set_wall_glitch(toggle: bool) -> None: ...
def get_wall_glitch() -> bool: ...

def set_disable_backface_culling(toggle: bool) -> None: ...
def get_disable_backface_culling() -> bool: ...

def set_disable_heli_blade_damage(toggle: bool) -> None: ...
def get_disable_heli_blade_damage() -> bool: ...

def get_time() -> int: ...
def set_time(time: int) -> None: ...

def get_hour() -> int: ...
def set_hour(hour: int) -> None: ...

def get_minute() -> int: ...
def set_minute(minute: int) -> None: ...

def get_weather() -> int: ...
def set_weather(weather: int) -> None: ...

def get_time_rate() -> int: ...
def set_time_rate(time_rate: int) -> None: ...

def get_gravity() -> float: ...
def set_gravity(gravity: float) -> None: ...

def get_gamespeed() -> float: ...
def set_gamespeed(gamespeed: float) -> None: ...

def get_water_level() -> float: ...
def set_water_level(water_level: float) -> None: ...

def get_max_flight_altitude() -> float: ...
def set_max_flight_altitude(max_flight_altitude: float) -> None: ...

def set_kill_command_delay(delay: int) -> None: ...
def get_kill_command_delay() -> int: ...

def disable_kill_command() -> None: ...
def enable_kill_command() -> None: ...

def get_vehicles_forced_respawn_height() -> float: ...
def set_vehicles_forced_respawn_height(height: float) -> None: ...

def add_player_class(
    team: int,
    color: RGB,
    skin: int,
    pos: Vector,
    angle: float,
    weapon: Optional[int] = None,
    ammo: Optional[int] = None,
    weapon1: Optional[int] = None,
    ammo1: Optional[int] = None,
    weapon2: Optional[int] = None,
    ammo2: Optional[int] = None,
) -> None: ...

def set_spawn_player_position(position: Vector) -> None: ...
def set_spawn_camera_position(position: Vector) -> None: ...
def set_spawn_camera_look_at(position: Vector) -> None: ...

def set_spawn_camera(
    position: Vector,
    look_yaw: float,
    look_pitch: float,
    range: Optional[float] = None,
) -> None: ...

def set_fall_timer(time: int) -> None: ...
def get_fall_timer() -> int: ... 

def get_wasted_settings() -> WastedSettings: ...
def set_wasted_settings(settings: WastedSettings) -> None: ...