from typing import Optional

class KeyBind:
    @property
    def slot(self) -> int: ...

    def __eq__(self, other: 'KeyBind') -> bool: ...
    def __hash__(self) -> int: ...

    @property
    def can_release(self) -> bool: ...

    @property
    def key(self) -> int: ...

    @property
    def key2(self) -> int: ...

    @property
    def key3(self) -> int: ...

def bindkey(
    can_release: bool,
    key: int,
    key2: Optional[int] = None,
    key3: Optional[int] = None,
) -> KeyBind: ...

def get_bindkey(slot: int) -> Optional[KeyBind]: ...

def remove_bind_key(slot: int) -> None: ...

def remove_all_key_binds() -> None: ...