# 可复用工作流：构建Rust项目并上传artifact
name: Build and Upload Artifact (Reusable)

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      arch:
        type: string
        required: true
      python-version:
        type: string
        required: true
    outputs:
      artifact-name:
        description: "名称"
        value: ${{ jobs.build.outputs.artifact-name }}

jobs:
  build:
    runs-on: ${{ inputs.os }}
    outputs:
      artifact-name: ${{ env.artifact_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build with Cargo
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries_${{ inputs.os }}_${{ inputs.arch }}_${{ inputs.python-version }}
          path: |
            target/release/*.dll
            target/release/*.so

      - name: Save Artifact Name to Output
        run: echo "artifact_name=libraries_${{ inputs.os }}_${{ inputs.arch }}_${{ inputs.python-version }}" >> $GITHUB_ENV