name: Build and Upload DLL

on:
  push:
    branches:
      - rwir
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
        arch: ['x64']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release

      - name: Move Libraries to build
        run: |
          mv target/release/*.dll build/
          mv target/release/*.so build/


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DLLs_${{ matrix.os }}_${{ matrix.arch }}
          path: |
            build/*.dll
            build/*.so

      - name: Save Artifact Names
        run: echo "artifact_name=DLLs_${{ matrix.os }}_${{ matrix.arch }}" >> $GITHUB_ENV
