name: Build and Upload DLL

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - uses: ./.github/actions/build-libraries
        with:
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}
