name: Daily Build and Upload DLL/SO

# 触发条件：master分支推送或手动触发（日常构建验证）
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
        arch: ['x64']
        python-version: ['3.10', '3.11', '3.12', '3.13']

    # 引用可复用工作流
    uses: ./.github/workflows/.build-and-upload.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      python-version: ${{ matrix.python-version }}