name: Build and Upload DLL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        arch: ['x64', 'x86']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 4.0.1

      - name: Clone Dependencies
        run: |
          git clone https://github.com/pybind/pybind11.git

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: |
          if [ "$ARCH" = "x64" ]; then
            cmake -G "Visual Studio 17 2022" -A x64 -S . -B build -DCMAKE_BUILD_TYPE=Release
          else
            cmake -G "Visual Studio 17 2022" -A Win32 -S . -B build -DCMAKE_BUILD_TYPE=Release
          fi
        shell: bash
        env:
          ARCH: ${{ matrix.arch }}

      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DLLs-${{ matrix.os }}-${{ matrix.arch }}
          path: build/