name: Docker Preview Build (next tag)

# 触发条件：master分支推送（推送预览版Docker镜像）
on:
  push:
    branches: [ master ]

jobs:
  # 1. 构建artifact（复用工作流）
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: ['x64']
        python-version: ['3.13']

    uses: ./.github/workflows/.build-and-upload.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      python-version: ${{ matrix.python-version }}

  # 2. 构建并推送Docker预览版
  build-multiarch:
    runs-on: ubuntu-latest
    needs: build_and_upload
    steps:
      - uses: actions/checkout@v4

      # 处理artifact（复用复合动作）
      - name: Process Artifacts
        uses: ./.github/actions/process-artifacts
        with:
          artifact-name: ${{ needs.build_and_upload.outputs.artifact-name }}
          output-dir: libraries

      # 推送Docker预览版（标签为next）
      - name: Build and Push Docker (next)
        uses: ./.github/actions/build-docker
        with:
          tags: atianxiua/vcmp-python:next