
name: Docker build

on:
  push: 
    branches: [ master ]

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: ['x64']
        python-version: ['3.13']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 4.0.1

      - name: Clone Dependencies
        run: |
          git clone https://github.com/pybind/pybind11.git

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: |
          if [ "$ARCH" = "x64" ]; then
            cmake -G "Visual Studio 17 2022" -A x64 -S . -B build -DCMAKE_BUILD_TYPE=Release
          else
            cmake -G "Visual Studio 17 2022" -A Win32 -S . -B build -DCMAKE_BUILD_TYPE=Release
          fi
        shell: bash
        env:
          ARCH: ${{ matrix.arch }}

      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: |
            # 下载并安装指定版本的 glibc
            wget http://ftp.gnu.org/gnu/libc/glibc-2.31.tar.gz
            tar -xvzf glibc-2.31.tar.gz
            cd glibc-2.31
            mkdir build && cd build
            ../configure --prefix=/opt/glibc-2.31
            make -j$(nproc)
            sudo make install
            cd ../..
  
            # 下载并安装指定版本的 GCC（包含对应的 glibcxx）
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
            sudo apt-get update && sudo apt-get install -y gcc-12 g++-12
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
  
            # 设置运行时路径，确保使用指定版本的 glibc 和 glibcxx
            export LD_LIBRARY_PATH=/opt/glibc-2.31/lib:$LD_LIBRARY_PATH
  
            # 验证安装的 glibc 和 glibcxx 版本
            strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
            strings /opt/glibc-2.31/lib/libc.so.6 | grep GLIBC
  
            # 配置 CMake
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ \
              -DCMAKE_C_FLAGS="-Wl,--rpath=/opt/glibc-2.31/lib -L/opt/glibc-2.31/lib" \
              -DCMAKE_CXX_FLAGS="-Wl,--rpath=/opt/glibc-2.31/lib -L/opt/glibc-2.31/lib"
  
      - name: Build with CMake
        run: |
          cmake --build build --config Release

      - name: Move DLLs to build (Windows)
        if: runner.os == 'Windows'
        run: |
          mv build/Release/*.dll build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DLLs_${{ matrix.os }}_${{ matrix.arch }}_${{ matrix.python-version }}
          path: |
            build/*.dll
            build/*.so

      - name: Save Artifact Names
        run: echo "artifact_name=DLLs_${{ matrix.os }}_${{ matrix.arch }}_${{ matrix.python-version }}" >> $GITHUB_ENV
    
  build-multiarch:
    runs-on: ubuntu-latest
    needs: build_and_upload
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: List Artifacts
        run: |
          echo "Artifacts available: ${{ needs.build_and_upload.outputs.artifact_name }}"
  
      - name: Download DLL Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_and_upload.outputs.artifact_name }} # 动态获取工件名称
          path: ./dl_libraries

      - name: Move downloaded DLLs to libraries folder and clean empty folders
        run: |
          mkdir -p libraries

          cp dl_libraries/**/*.so libraries/

          rm -rf dl_libraries
          
      - name: List Artifacts after download
        run: ls -a ./libraries

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            atianxiua/vcmp-python:next
          platforms: linux/amd64