name: Docker build

on:
  push: 
    branches: [ master ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['x64']
        python-version: ['3.13']
        glibc-version: ['2.31', '2.33', '2.35'] # 支持更多 glibc 版本
        gcc-version: ['10', '11', '12']         # 支持更多 gcc/glibcxx 版本
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 4.0.1

      - name: Install GCC and glibc
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          
          # 安装指定版本的 GCC
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update && sudo apt-get install -y gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }}
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gcc-version }} 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.gcc-version }} 100
          
          # 安装指定版本的 glibc
          wget http://ftp.gnu.org/gnu/libc/glibc-${{ matrix.glibc-version }}.tar.gz
          tar -xvzf glibc-${{ matrix.glibc-version }}.tar.gz
          cd glibc-${{ matrix.glibc-version }}
          mkdir build && cd build
          ../configure --prefix=/opt/glibc-${{ matrix.glibc-version }}
          make -j$(nproc)
          sudo make install
          
          # 设置运行时路径
          sudo ldconfig /opt/glibc-${{ matrix.glibc-version }}/lib
          export LD_LIBRARY_PATH=/opt/glibc-${{ matrix.glibc-version }}/lib:$LD_LIBRARY_PATH

      - name: Configure and Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_C_FLAGS="-Wl,--rpath=/opt/glibc-${{ matrix.glibc-version }}/lib -L/opt/glibc-${{ matrix.glibc-version }}/lib" \
            -DCMAKE_CXX_FLAGS="-Wl,--rpath=/opt/glibc-${{ matrix.glibc-version }}/lib -L/opt/glibc-${{ matrix.glibc-version }}/lib"
          cmake --build build --config Release