
name: Docker build

on:
  push: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Libraries (with Setup Python)
        uses: ./.github/actions/build-libraries
        with:
          python-version: 3.13
          os: ubuntu-22.04
        id: build_libraries

      - name: Download Libraries
        uses: ./.github/actions/download-libraries
        with:
          artifacts: ${{ needs.build_libraries.outputs.artifact_name }}
          output_target: libraries

      - name: Build Docker Image
        uses: ./.github/actions/build-docker-image
        with:
          hub_username: ${{ secrets.HUB_USERNAME }}
          hub_password: ${{ secrets.HUB_PASSWORD }}
          tags: |
            atianxiua/vcmp-python:next