name: Create tagged release and publish to PyPI

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Download DLLs and SOs
        uses: actions/download-artifact@v3
        with:
          name: DLLs-*
          path: ./dlls
      - name: Create release
        run: npx changelogithub-chinese
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Upload DLLs and SOs to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dlls/*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Copy DLLs and SOs to package directory
        uses: actions/download-artifact@v3
        with:
          name: DLLs-*
          path: ./dlls
      - name: Build and publish package
        run: |
          # 将 DLLs 和 SOs 添加到包中
          python setup.py sdist bdist_wheel
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}