name: Build and Upload DLL & Create tagged release and publish to PyPI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
        arch: ['x64']
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Libraries
        uses: ./.github/actions/build-libraries
        with:
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}


  release_and_publish:
    # 发布到 GitHub Release 和 PyPI
    runs-on: ubuntu-latest
    needs: build_and_upload

    steps:
      - uses: actions/checkout@v4

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Download Libraries
        uses: ./.github/actions/download-libraries
        with:
          artifacts: ${{ needs.build_and_upload.outputs.artifact_name }}
          output_target: libraries

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Create release
        run: npx changelogithub-chinese
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Set up Python for PyPI
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies for PyPI
        run: |
          python -m pip install --upgrade pip
          pip install pdm twine

      - name: Build and publish package to PyPI
        run: |
          pdm build
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: Upload DLL to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./libraries/*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Build Docker Image
        uses: ./.github/actions/build-docker-image
        with:
          tags: |
            atianxiua/vcmp-python:latest
            atianxiua/vcmp-python:${{ env.RELEASE_VERSION }}