name: Release to GitHub+PyPI+Docker

# 触发条件：标签推送（v*）或手动触发（正式发布）
on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  # 1. 构建artifact（复用工作流）
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
        arch: ['x64']
        python-version: ['3.10', '3.11', '3.12', '3.13']

    uses: ./.github/workflows/.build-and-upload.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      python-version: ${{ matrix.python-version }}

  # 2. 发布流程（依赖构建结果）
  release_and_publish:
    runs-on: ubuntu-latest
    needs: build_and_upload
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # 处理artifact（复用复合动作）
      - name: Process Artifacts
        uses: ./.github/actions/process-artifacts
        with:
          artifact-name: ${{ needs.build_and_upload.outputs.artifact-name }}
          output-dir: libraries

      - name: Copy to Source Directory
        run: |
          mkdir -p ./src/vcmp/libraries
          cp -r libraries/* ./src/vcmp/libraries

      # 创建GitHub Release
      - name: Create GitHub Release
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npx changelogithub-chinese
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      # 发布到PyPI
      - name: Publish to PyPI
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: |
          python -m pip install --upgrade pip
          pip install pdm twine
          pdm build
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      # 上传artifact到GitHub Release
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./libraries/*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      # 构建并推送Docker（正式标签）
      - name: Build and Push Docker
        uses: ./.github/actions/build-docker
        with:
          tags: |
            atianxiua/vcmp-python:latest
            atianxiua/vcmp-python:${{ env.RELEASE_VERSION }}